**Welcome to numPy tutorial**

In [1]:
import numpy as np

In [2]:
myarr=np.array([[2,3,4,5,7]],np.int64)

In [3]:
myarr

array([[2, 3, 4, 5, 7]], dtype=int64)

In [4]:
myarr.dtype

dtype('int64')

In [5]:
myarr.shape

(1, 5)

In [6]:
myarr[0]

array([2, 3, 4, 5, 7], dtype=int64)

In [7]:
myarr[0,3]

5

In [8]:
myarr[0,3]=45

In [9]:
myarr

array([[ 2,  3,  4, 45,  7]], dtype=int64)

**Array structure: conversion from other Python structures**

In [10]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
listarray.dtype

dtype('int32')

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [18]:
zeros=np.zeros((3,5))

In [19]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.array({1,2,3,4,5})

array({1, 2, 3, 4, 5}, dtype=object)

In [24]:
np.__version__

'1.25.2'

In [25]:
rng=np.arange(12)

In [26]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
lspace=np.linspace(1,5,12)

In [28]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [30]:
emp=np.empty((4,6))

In [31]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.78020712e-306, 1.42419938e-306, 7.56603881e-307],
       [8.45603441e-307, 1.42417221e-306, 1.60219306e-306,
        6.23059726e-307, 1.06811422e-306, 1.42417221e-306],
       [1.37961641e-306, 9.45697982e-308, 8.01097889e-307,
        1.78020169e-306, 7.56601165e-307, 1.02359984e-306],
       [1.33510679e-306, 2.22522597e-306, 1.11260144e-306,
        6.89812281e-307, 2.22522596e-306, 8.34443015e-308]])

In [32]:
emp_like=np.empty_like(lspace)

In [33]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [34]:
ide=np.identity(45)

In [35]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [36]:
ide.size

2025

In [37]:
ide.shape

(45, 45)

In [39]:
ide.dtype

dtype('float64')

In [42]:
arr=np.arange(99)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [45]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [46]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [67]:
arr.size

9

In [47]:
arr.shape

(99,)

In [52]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [53]:
arr=np.array(x)

In [54]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [56]:
arr.sum(axis=0)

array([12,  8,  9])

In [57]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [58]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [60]:
arr.flat

In [62]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [63]:
arr.ndim

2

In [68]:
value=np.array([1,23,123,4,2])

In [69]:
value

array([  1,  23, 123,   4,   2])

In [71]:
value.argmax()

2

In [72]:
value.argmin()

0

In [73]:
value.argsort()

array([0, 4, 3, 1, 2], dtype=int64)

In [74]:
ar1=np.array([[1,2,3,4],[5,6,7,8],[2,4,5,6]])

In [75]:
ar1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 4, 5, 6]])

In [76]:
ar2=np.array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 4, 5, 6]])

In [77]:
ar2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 4, 5, 6]])

In [79]:
r=ar1+ar2

In [80]:
r

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [ 4,  8, 10, 12]])

In [81]:
r.size

12

In [82]:
r.shape

(3, 4)

In [83]:
r.argmax()

7

In [88]:
value_of_matrix=np.sqrt(r)

In [89]:
value_of_matrix

array([[1.41421356, 2.        , 2.44948974, 2.82842712],
       [3.16227766, 3.46410162, 3.74165739, 4.        ],
       [2.        , 2.82842712, 3.16227766, 3.46410162]])

In [90]:
value_of_matrix.sum

<function ndarray.sum>

In [91]:
value_of_matrix.sum()

34.51497349203486

In [93]:
value_of_matrix.argmin()

0

In [94]:
value_of_array=np.array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [ 4,  8, 10, 12]])

In [95]:
value_of_array

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [ 4,  8, 10, 12]])

In [98]:
type

(array([1, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 3, 2, 3], dtype=int64))

In [100]:
np.count_nonzero(value_of_array)

12

In [101]:
np.nonzero(value_of_array)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [102]:
import sys

In [103]:
py_arr=[0,4,55,2]

In [104]:
np_arr=np.array(py_arr)

In [105]:
sys.getsizeof(1)*len(py_arr)

112

In [106]:
np_arr.itemsize*np_arr.size

16